name: CI - Build script in a Docker Image

on:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: user/app:latest
      #     build-args: |
      #       arg1=value1
      #       arg2=value2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.dockerdev/Dockerfile
          tags: luciotbc/dotfiles:latest
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUBTOKEN }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
# jobs:
#   build:
#     runs-on: ubuntu-20.04
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 1
#       - 
#         name: Build and Publish Tag Docker image
#         uses: VaultVulp/gp-docker-action@1.1.7
#         with:
#           github-token: ${{ secrets.GITHUBTOKEN }}
#           image-name: dotfiles
#           build-context: .dockerdev
#           extract-git-tag: true # Provide flag to extract Docker image tag from git reference

      # -
      #   name: Build
      #   run: |
      #     docker build .dockerdev/Dockerfile

      # -
      #   name: Install dotfiles
      #   run: |
      #     docker-compose run -u lucio base curl -sL https://raw.githubusercontent.com/luciotbc/dotfiles/lc-master/ci/_setup.sh | bash
