name: CI - Build script in a Docker Image

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      -
        name: Build
        run: |
          docker-compose build

      -
        name: Install dotfiles
        run: |
          docker-compose run -u lucio base curl -sL https://raw.githubusercontent.com/luciotbc/dotfiles/lc-master/ci/_setup.sh | bash
